# Generated by Django 4.2.3 on 2023-10-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_publisher_booksale'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booksale',
            table='booksale',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
