# Generated by Django 4.2.3 on 2023-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_alter_booksale_table_alter_publisher_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_title_book'),
        ),
    ]
